### PR TITLE
Use 7.0 rather than 7

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by aik099** [comment]
The change would prevent PHP 7.1 to be used instead of PHP 7.0, when PHP 7.1 will be released I presume?

**Comment by GrahamCampbell** [comment]
It does prevent 7.1, on purpose. You still want to test on 7.0 when 7.1 comes out.

**Comment by Jean85** [comment]
:+1:

**Comment by everzet** [comment]
Thank you very much for contribution!

**Pull request merged**
