### PR TITLE
Issue #451: Raise minimum version of sebastian/comparator.

### PR DESCRIPTION
**Pull request by drupol**
This PR:

* [x] Relates to #451

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Why is this not an issue in prophecy’s CI?

**Comment by drupol** [comment]
It does fail locally: https://pastebin.com/k5ZP4vpN

**Comment by drupol** [comment]
See https://github.com/phpspec/prophecy/pull/453

**Comment by ciaranmcnulty** [comment]
ok, I can't see any BC breaks in comparator 👍 

Could we allow 2.x too?

**Comment by ciaranmcnulty** [comment]
I didn't realise that raising the phpspec version would drop out the old versions of PHP 🤦‍♂ 

Will revert in master

**Pull request merged**
