### PR TITLE
#527 Fix. Add static type

### PR DESCRIPTION
**Pull request by denis-rolling-scopes**

### CODE REVIEW

**Comment by keradus** [comment]
@ciaranmcnulty any chance to have this fix released?

**Comment by soyuka** [comment]
:+1: we need this in API Platform too :)

**Comment by keradus** [comment]
kudos for providing the change, @denis-rolling-scopes 🍻 
thanks for merging, @stof !

**Comment by Jean85** [comment]
For anyone wondering, this is released as 1.15

**Pull request merged**
