### PR TITLE
Bump phpdocumentor/reflection-docblock to ^5.0

### LINKED ISSUE #415: Add ^5 to allowed versions of phpdocumentor/reflection-docblock
Version 5 of reflection-docblock is coming out soon, and currently code that uses its new features will not be compatible with prophecy.

### PR DESCRIPTION
**Pull request by ricpelo**
Fixes #415.

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
As the tests pass, this seems harmless right? Thanks @ricpelo

**Comment by Miclef1** [comment]
> As the tests pass, this seems harmless right? Thanks @ricpelo

This is not harmless.
You have introduced a new major version dependency with a minor version update of your project, which - to my understanding - violates the principle of semantic versioning.

We currently have an issue with this.
See following error message:
`phpdocumentor/reflection-docblock 5.0.0 requires ext-filter ^7.1 -> the requested PHP extension filter has the wrong version (7.2.12) installed.`

**Comment by stof** [comment]
We allow the new version of the dependency. But we don't force using it. Composer will still resolve compatible dependencies.

**Comment by stof** [comment]
btw, the message looks weird. `7.2.12` matches the `^7.1` constraint.

**Pull request merged**
