### PR TITLE
Capturing bug with PHP7 return typehinting and spies

### PR DESCRIPTION
**Pull request by Sam-Burns**
Capturing bug with integration test, pending clearer idea of which class/unit test is relevant

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Ref https://github.com/phpspec/prophecy/issues/250

**Comment by Sam-Burns** [comment]
I really don't think you will want to merge this pull request, but @everzet was asking for a test capturing the bug in the Prophecy repo.  Any guidance as to which class is responsible for the bug, and which spec this can be moved to, would be very much appreciated.

**Comment by aik099** [comment]
Can you please change your test to use PHPSpec instead of PHPUnit?

**Comment by Sam-Burns** [comment]
@aik099 No, because it's not clear to me what class the bug is in.  Do you know the answer to that?

**Comment by aik099** [comment]
No.

**Comment by Sam-Burns** [comment]
@aik099 On the original bug report (https://github.com/phpspec/prophecy/issues/250) @everzet asked me to put a test in the repo.  I suggest we leave it as it is for now, until someone comes along who knows which spec this can be transferred to.  Then we can get rid of the PHPUnit installation and the integration test, and capture the buggy behaviour in a unit test instead.

Alternatively, I could use Behat to write an integration test, but I'm not sure if that improves the situation at all.

**Comment by everzet** [comment]
@Sam-Burns this is perfect, Sam. Working on it

**Comment by everzet** [comment]
Ok. I don't see a problem here. In my view, Prophecy acts exactly like it should.

You double `CollaboratorWithReturnTypehinting::getAnInt(): int`. Double calls do nothing - return `null` by default. If you do not explicitly tell it to return a particular integer, it would break the type hint, yes.

Doing logical here:

```php
    $subject->getAnInt()->willReturn(42);
    $this->getAnIntFromThisThing($subject);
    $subject->getAnInt()->shouldHaveBeenCalled();
```

fixes the fatal. As it should.

**Comment by ciaranmcnulty** [comment]
This is inconsistent, IIRC prophecy is returning non-null object instances where return type hints are used

**Comment by everzet** [comment]
@ciaranmcnulty I am not aware of such behaviour.

**Comment by jakzal** [comment]
> prophecy is returning non-null object instances where return type hints are used

What do you think of implementing such a behaviour? I mean returning dummies of objects and "empty" values for simple types (0, '', false).

**Pull request closed without merging**
