### PR TITLE
Variadics support

### PR DESCRIPTION
**Pull request by pamil**
Based on #125 and #143. Also fixes #231 and #91.

### CODE REVIEW

**Comment by pamil** [comment]
Failing on HHVM, any ideas?

**Comment by everzet** [comment]
Nope. Could you debug?

**Comment by pamil** [comment]
@everzet should be passing now, there were default values set for variadic parameters, [which is also invalid in PHP](https://wiki.php.net/rfc/variadics#syntactic_restrictions), but it seems like there isn't any error if you do so :)

**Comment by pjedrzejewski** [comment]
@everzet @ciaranmcnulty Hey guys, could you have a quick look at this? We tested this on a project and works well. :) Thanks!

**Comment by Daveawb** [comment]
Lack of this support is holding our project up at the moment. Review of this ASAP would be really helpful.

**Comment by ChadSikorra** [comment]
Nice! This PR fixes all my failing specs in PHP7 that need variadic support.

**Comment by syhol** [comment]
I also really would like this in. Now its working on hhvm, @everzet can you let us know what you think? :smile:

I just refactored my ACL to use variadics and its being mocked throughout a bunch of my specs, so a good chunk of my tests wont work without this. It's just sitting on a branch that I rebase daily... :cry:

**Comment by pamil** [comment]
@everzet @ciaranmcnulty @stof ping, also for #238, those PRs are ready to go :)

**Comment by pamil** [comment]
Ping pong :pineapple:

**Comment by lchrusciel** [comment]
When it will be merged? I would love to have this ASAP.

**Comment by sukei** [comment]
+1

**Comment by pamil** [comment]
Do you need some help with maintaining this repository? Seems like #125 had initially implemented it over a year ago and it just can't get merged.

**Comment by Daveawb** [comment]
@everzet lack of response here is starting to make me wonder how serious phpspec/prophecy is as a bdd framework. As @pamil suggested, do you need some assistance maintaining this repository?

**Comment by aik099** [comment]
For now I suggest to do following:

1. fork the repo
2. create a branch in a form
3. on that branch merge this PR
4. in your `composer.json` specify repo override so that your fork is used instead of main repo

This approach usually allows me to continue using the any library until the PR is merged.

**Comment by MitchProbst** [comment]
Is there a reason this hasn't been merged in yet?

**Comment by Daveawb** [comment]
@everzet at last! Thank you!

**Pull request merged**
