### PR TITLE
Declare PHP 8.4 compatibility

### LINKED ISSUE #624: PHP 8.4 support
I started testing Drupal 11 with PHP 8.4 and faced issues because of https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

I did patch some code (will provide PR) but still getting deprecation warnings from mocks

Probably the `\Prophecy\Doubler\ClassPatch\DisableConstructorPatch::apply()` needs changes

```
    OK (6 tests, 154 assertions)
    
    Other deprecation notices (2)
    
      1x:
    Double\Drupal\Core\Cache\Context\CacheContextsManager\P1::__construct():
    Implicitly marking parameter $container as nullable is deprecated, the
    explicit nullable type must be used instead
        1x in VariationCacheTest::setUp from Drupal\Tests\Core\Cache
    
      1x:
    Double\Drupal\Core\Cache\Context\CacheContextsManager\P1::__construct():
    Implicitly marking parameter $contexts as nullable is deprecated, the
    explicit nullable type must be used instead
        1x in VariationCacheTest::setUp from Drupal\Tests\Core\Cache
```

### PR DESCRIPTION
**Pull request by andypost**
Closes #624

### CODE REVIEW

**Review by W0rma — APPROVED** [review]

**Review by Jean85 — APPROVED** [review]
:tada:

**Comment by Jean85** [comment]
I can report that I'm successfully using `master` with no issues under PHP 8.4: https://github.com/facile-it/paraunit/pull/279

**Comment by stof** [comment]
@andypost please also update the CI config to have a job running on PHP 8.4

**Comment by andypost** [comment]
@stof there's already https://github.com/phpspec/prophecy/blob/master/.github/workflows/build.yml#L24-L25

but to move it above phpspec needs new release

**Pull request merged**
