### PR TITLE
Hotfix #368: Optional nullable array parameter with not null default value

### LINKED ISSUE #368: optional array parameter causes incompatible prototype generation
Raw error message I get when running phpspec:
```
- it produces a result item with a path to the work route
      warning: Declaration of Double\EMA\MD\Domain\Model\Work\Work\P5::fromNative(string $contentId, string $originalTitle,
      string $workType, string $birthday, string $durationSpec, string $countryOfOrigin, string $language, string $title,
      ?string $identifier = NULL, array $alternateIdentifiers = Array): EMA\MD\Domain\Model\Work\Work should be compatible
      with EMA\MD\Domain\Model\Work\Work::fromNative(string $contentId, string $originalTitle, string $workType, string
      $birthday, string $durationSpec, string $countryOfOrigin, string $language, string $title, ?string $identifier = NULL,
      ?array $alternateIdentifiers = Array): EMA\MD\Domain\Model\Work\Work in
      /var/www/html/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49)
       0 vendor/phpspec/phpspec/src/PhpSpec/Runner/Maintainer/ErrorMaintainer.php:121
         throw new PhpSpec\Exception\Example\ErrorException("warning: Declaration of D...")
       1 vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php:49
         eval()
       2 vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:142
         Prophecy\Doubler\Generator\ClassCreator->create("Double\EMA\MD\Domain\Mode...", [obj:Prophecy\Doubler\Generator\Node\ClassNode])
       3 vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:105
         Prophecy\Doubler\Doubler->createDoubleClass([obj:ReflectionClass], [array:0])
       4 vendor/phpspec/prophecy/src/Prophecy/Doubler/LazyDouble.php:122
         Prophecy\Doubler\Doubler->double([obj:ReflectionClass], [array:0])
       5 vendor/phpspec/prophecy/src/Prophecy/Prophecy/ObjectProphecy.php:114
         Prophecy\Doubler\LazyDouble->getInstance()
       6 vendor/phpspec/prophecy/src/Prophecy/Prophecy/MethodProphecy.php:49
         Prophecy\Prophecy\ObjectProphecy->reveal()
       7 vendor/phpspec/prophecy/src/Prophecy/Prophecy/ObjectProphecy.php:256
         Prophecy\Prophecy\MethodProphecy->__construct([obj:Prophecy\Prophecy\ObjectProphecy], "contentId", [obj:Prophecy\Argument\ArgumentsWildcard])
       8 vendor/phpspec/phpspec/src/PhpSpec/Wrapper/Collaborator.php:69
         Prophecy\Prophecy\ObjectProphecy->__call("contentId", [obj:Prophecy\Argument\ArgumentsWildcard])
       9 [internal]
         spec\App\Infrastructure\Assembler\DoctrineWorkResultItemAssemblerSpec->it_produces_a_result_item_with_a_path_to_the_work_route([obj:PhpSpec\Wrapper\Collaborator], [obj:PhpSpec\Wrapper\Collaborator], [obj:PhpSpec\Wrapper\Collaborator])
      10 vendor/phpspec/phpspec/src/PhpSpec/Runner/ExampleRunner.php:150
         ReflectionMethod->invokeArgs([obj:spec\App\Infrastructure\Assembler\DoctrineWorkResultItemAssemblerSpec], [array:3])
      11 vendor/symfony/console/Application.php:906
         Symfony\Component\Console\Command\Command->run([obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
      12 vendor/symfony/console/Application.php:224
         Symfony\Component\Console\Application->doRunCommand([obj:PhpSpec\Console\Command\RunCommand], [obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
      13 vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php:89
         Symfony\Component\Console\Application->doRun([obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
      14 vendor/phpspec/phpspec/bin/phpspec:25
         Symfony\Component\Console\Application->run()
      15 vendor/phpspec/phpspec/bin/phpspec:27
         {closure}("4.2.0")

```

Diff between signatures

```diff
- fromNative(…, ?string $identifier = NULL, array $alternateIdentifiers = Array): …
+ fromNative(…, ?string $identifier = NULL, ?array $alternateIdentifiers = Array): …
```

Notice how things are ok for the `$identifier` parameter, which is of type string.

### PR DESCRIPTION
**Pull request by webimpress**
Resolves #368 

~So far I have no idea how to write tests to prove the fix, but I tested it locally with my code and it works as expected.~

Update : test added :smile:

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
This looks good to me 👍

**Comment by webimpress** [comment]
@ciaranmcnulty will you be able to release it soon?

**Comment by scheb** [comment]
Just ran into this issue. Would be great to get it into a release.

**Comment by ciaranmcnulty** [comment]
Thank you @webimpress!

**Pull request merged**
