### PR TITLE
Document arguments to willReturn

### LINKED ISSUE #552: func_get_args() use of willReturn() lacks proper annotation
Please add either an annotation or move to PHP variadics.

Otherwise static analysers will choke on every call of willReturn()

### PR DESCRIPTION
**Pull request by neclimdul**
Fixes #552

### CODE REVIEW

**Comment by neclimdul** [comment]
variadic makes more sense to me but went with the annotation to match similar behavior in Argument::allOf

**Comment by stof** [comment]
As the min supported version is now PHP 7.2, please use a variadic signature instead (the initial implementation was done with support for PHP 5.3).

**Comment by stof** [comment]
@neclimdul any chance to update your PR ?

**Comment by neclimdul** [comment]
@stof rebased and applied the variadic natively. Docs left for phpstan.

**Review by stof — APPROVED** [review]

**Pull request merged**
