### PR TITLE
Tentatively support php8

### PR DESCRIPTION
**Pull request by staabm**
In the process of getting composer/composer ready for php8, see https://github.com/composer/semver/pull/91

- [ ] requires https://github.com/doctrine/instantiator/pull/67

### CODE REVIEW

**Comment by alexpott** [comment]
We need to fix the call to $parameter->getClass() and $parameter->isArray() and $parameter->isCallable() in \Prophecy\Doubler\Generator\ClassMirror

These method are deprecated in PHP 8.

**Comment by staabm** [comment]
I dont plan to continue working on this. feel free to take over this PR

**Comment by ciaranmcnulty** [comment]
I have a branch that removes the deprecations, waiting to merge #476 first before proceeding as they overlap

**Comment by GrahamCampbell** [comment]
This PR can be closed, I think?

**Comment by ciaranmcnulty** [comment]
Thanks for contributing @staabm. Even though it's not merged it helped move the conversation along!

**Pull request closed without merging**
