### PR TITLE
Allow reflection-docblock v4

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by Taluu** [comment]
How about using the real or notation of composer (`||` instead of `|`) while you're at it ?

**Comment by GrahamCampbell** [comment]
I prefer the single bar notation. :P (I don't think the double one is a replacement, just an alternative?)

**Comment by Taluu** [comment]
Actually both are indeed supported, but in [the docs](https://getcomposer.org/doc/articles/versions.md#version-range) there's no mention of `|`, which could mean IMO that this is "kind of deprecated" / "hidden".

**Comment by derrabus** [comment]
The single pipe is consistent with the rest of the file. It's a deprecated notation, but it will probably be supported forever. 😉

**Comment by jaapio** [comment]
It would be very nice if this can be merged soon. It is blocking new developments in phpdocumentor itself now :-(

**Comment by GrahamCampbell** [comment]
Ping @everzet. ;)

**Comment by everzet** [comment]
@GrahamCampbell thanks for contribution

**Pull request merged**
