### PR TITLE
Break external references to Call arguments

### LINKED ISSUE #75: Problem with predictions check
As it stands now, predictions are checked on teardown. Since call center records calls with reference to arguments, operations on these arguments after the call lead to unexpected results.
Here's an example that gives me this issue:

```
// example
function it_makes_proper_collaborator_call($collaborator)
{
   $collaborator->execute(Argument::which('getName', 'A'))->shouldBeCalled();
   $this->run();
}

//implementation
function run()
{
  $event = new Event();
  $event->setName('A');
  $this->collaborator->execute($event);
  $event->setName('B');
}
```

It fails, because when predictions are checked the `$event` has wrong `name`.

### PR DESCRIPTION
**Pull request by danizord**
Attempt to fix #75

### CODE REVIEW

**Comment by stof** [comment]
This has 2 issues:

- passing non-serializable objects is a necessary use case
- this breaks the ``ExactToken`` matching when using a spy

**Comment by danizord** [comment]
Hey @stof! Is there any other way to solve this issue?

**Comment by stof** [comment]
there is no *easy* way to solve it

**Comment by everzet** [comment]
This one is part of some of my nightmares, sadly. My guess would be that the solution would require major rethink of couple of core components, and, hence the major version bump.

**Pull request closed without merging**
