### PR TITLE
Added mustReturn() method to MethodProphecy

### PR DESCRIPTION
**Pull request by horak-m**
Method combines willReturn() call with shouldBeCalled() which is frequently used together.

### CODE REVIEW

**Comment by Taluu** [comment]
Not really sure if it's semantically correct (`mustReturn`). I don't think this will be interpreted as "will return and should be called at least once". So IMO it's fine like this.

**Comment by Deuchnord** [comment]
Why not calling it `shouldBeCalledAndReturn()`?

**Comment by stof** [comment]
I'm not convinced this is needed (and I'm not sure about the "frequently used together". I think I almost never used them together).

**Comment by meridius** [comment]
Well, @stof, we use them together in our team almost every time. It is safer than just `willReturn()` alone because added `shouldBeCalled()` ensures that object not only returns expected result if asked, but also makes sure that the call on it is made. Thus preventing any unnecessary promises.

**Comment by Deuchnord** [comment]
I use `shouldBeCalled()` and `willReturn()` together frequently too, but I'm not sure creating one new method doing both of them is really useful… After all, we can already combine them in our tests.

**Comment by meridius** [comment]
Yes, we can combine them manually for each and every promise but using that alias is so much easier.

**Comment by ciaranmcnulty** [comment]
I agree with @stof, I don't want to encourage this and don't think it's a problem not having it

**Pull request closed without merging**
