### PR TITLE
Add __invoke to allowed reflectable methods list

### PR DESCRIPTION
**Pull request by ftrrtf**
related to https://github.com/phpspec/prophecy/issues/205

### CODE REVIEW

**Comment by stof** [comment]
this should be covered by a test to avoid regressions

**Comment by ftrrtf** [comment]
@stof updated

**Comment by mente** [comment]
+1

**Comment by tPl0ch** [comment]
:+1:

**Comment by iztoksvetik** [comment]
+1

**Comment by EricReiche** [comment]
+1

**Pull request merged**
