### PR TITLE
Document consecutive return feature

### PR DESCRIPTION
**Pull request by mbrodala**
See https://gist.github.com/gquemener/292e7c5a4bbb72fd48a8#gistcomment-1222753

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Minot sure we should encourage this

**Comment by everzet** [comment]
This functionality is intentionally not exposed.

**Comment by mbrodala** [comment]
@everzet And what is the intention if I may ask? :-)

**Comment by aik099** [comment]
Maybe because it allows to do the `structure binding` (preffered way in Mockery) instead of doing `message binding` (preffered way in Prophecy) as described in http://everzet.com/post/72910908762/conceptual-difference-between-mockery-and-prophecy.

If I'm correct, then using `->willReturn(1, 3, 4, ...)` technique would make your test suite aware of tested code internals thus making it more brittle.

**Comment by mbrodala** [comment]
@aik099 Makes perfect sense, thanks. I'll watch out for this.

**Pull request closed without merging**
