### PR TITLE
Tweak the doctrine instantiator version

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by kirkbushell** [comment]
This breaks composer installs for phpspec.

**Comment by kirkbushell** [comment]
It's also happening on the phpspec/phpspec repository.

**Comment by GrahamCampbell** [comment]
Update your composer version.

**Comment by brendo** [comment]
> Update your composer version.

How? After I've run `composer self-update`, which puts me on [https://github.com/composer/composer/commit/4ca9e602a9a0ef7639ad143b6366b71638c77029](this commit), I still receive the error.

**Comment by stof** [comment]
@brendo Composer is not tagging regularly (it is complaining about outdated phar much earlier than it releases). They recommend using the uptodate phar for now

**Pull request merged**
